name: tests

on: [push, pull_request]

jobs:
    lint:
        name: Source code linting and unit testing
        runs-on: ubuntu-latest
        steps:
            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.4

            -
                uses: actions/checkout@v4

            -
                name: Validate composer.json
                run: composer validate

            -
                name: Cache composer dependencies
                uses: actions/cache@v4
                with:
                    path: ~/.composer/cache
                    key: composer-php-8.4

            -
                name: Install composer dependencies
                run: composer install --prefer-dist --no-progress

            -
                name: PHP Linting
                run: composer lint:php

            -
                name: Editorconfig Linting
                run: composer lint:editorconfig

    unittest:
        runs-on: ubuntu-latest

        strategy:
            max-parallel: 2
            matrix:
                php-version: [8.4, 8.3]

        name: Unit (PHP ${{ matrix.php-version }})
        steps:
            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}

            -
                uses: actions/checkout@v4

            -
                name: Validate composer.json
                run: composer validate

            -
                name: Cache composer dependencies
                uses: actions/cache@v4
                with:
                    path: ~/.composer/cache
                    key: composer-php-${{ matrix.php-version }}

            -
                name: Install composer dependencies
                run: composer install --prefer-dist --no-progress

            -
                name: PHP Unit Testing
                run: composer test:php
