name: tests

on: [push, pull_request]

jobs:
    lint:
        name: Source code linting
        runs-on: ubuntu-latest
        steps:
            -
                uses: actions/checkout@v2

            -
                name: Validate composer.json
                run: composer validate

            -
                name: Cache composer dependencies
                uses: actions/cache@v1
                with:
                    path: ~/.composer/cache
                    key: composer

            -
                name: Install composer dependencies
                run: composer install --prefer-dist --no-progress --no-suggest

            -
                name: PHP Linting
                run: composer lint:php

            -
                name: Editorconfig Linting
                run: composer lint:editorconfig
